//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseExpressFEntities : DbContext
    {
        public DatabaseExpressFEntities()
            : base("name=DatabaseExpressFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<CodigosBarras> CodigosBarras { get; set; }
        public virtual DbSet<ErpProductos> ErpProductos { get; set; }
        public virtual DbSet<ExpProductos> ExpProductos { get; set; }
        public virtual DbSet<ProductosCategorias> ProductosCategorias { get; set; }
        public virtual DbSet<TiposProducto> TiposProducto { get; set; }
        public virtual DbSet<VentaExpress> VentaExpress { get; set; }
    }
}
